#spring.application.name=blogger-box-backend
#spring.main.banner-mode=off
#server.port=7575

spring:
  application:
    name: blogger-box-backend
  main:
    banner-mode: off

  server:
    port : 7575

  
